services:
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=30 # Poll every 30 seconds
      -  WATCHTOWER_WATCHLIST=hungnguyen0811/express_1:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
  
  express_1: 
    build: . 
    ports: 
      - 8080:8080
    container_name: express_1 
    image: hungnguyen0811/express_1:latest

  

