name: Release Node.js app

on:
  push: 
    branches: 
     - main
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker BuildX
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker
      uses: docker/login-action@v3
      with: 
        username: hungnguyen0811
        password: dckr_pat_VHDcwf_SoWzjX68qDpkPt7HH6iA

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
          context: .
          push: true
          tags: hungnguyen0811/app:latest
